ALTER TABLE cards
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS imported_by TEXT NULL,
  ADD COLUMN IF NOT EXISTS mcq_distractors TEXT[] NULL,
  ADD COLUMN IF NOT EXISTS id_question TEXT NULL;